apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: data-api
  envs:
  - configmap.env
labels:
- pairs:
    app: data-api
  includeSelectors: true
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
